import { Button, VerticalBox , LineEdit} from "std-widgets.slint";

export component AppWindow inherits Window {
    background: #171717;
    GridLayout {
    padding: 50px;
    spacing: 25px;
     Row {
        Text {
            text: "Enter Total Income";
            horizontal-alignment: center;
            font-size: 24px;
            font-weight: 900;
        }
     }
     Row {
        LineEdit {
            font-size: 14 * 1px;
            horizontal-alignment: center;
            placeholder-text: "Enter Your Number";
            height: 35px;
        }

     }
     Row {
        Button {
            primary: true;
            text: "Calculate";
            height: 35px;
        }
     }
   }
}
